/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package present.admin;

import data.Log;
import domain.Usuario;
import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import present.login.TelaLogin;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Felipe
 */
public class TelaAdmin extends javax.swing.JFrame {
    Usuario user;
    /**
     * Creates new form TelaLogin
     * @param usuario
     */
    public TelaAdmin(Usuario usuario) {
        initComponents();
        this.user = usuario;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/present/admin/foto.jpg"));
        Image image = icon.getImage();
        dpnAreaTrabalhoAdmin = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuUsuarios = new javax.swing.JMenu();
        mnuCadatroUsuario = new javax.swing.JMenuItem();
        mnuExcluirUsuario = new javax.swing.JMenuItem();
        mnuAlterarUsuario = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenu();
        mnuCadastrarProduto = new javax.swing.JMenuItem();
        mnuRemoverProduto = new javax.swing.JMenuItem();
        mnuSessao = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        javax.swing.GroupLayout dpnAreaTrabalhoAdminLayout = new javax.swing.GroupLayout(dpnAreaTrabalhoAdmin);
        dpnAreaTrabalhoAdmin.setLayout(dpnAreaTrabalhoAdminLayout);
        dpnAreaTrabalhoAdminLayout.setHorizontalGroup(
            dpnAreaTrabalhoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        dpnAreaTrabalhoAdminLayout.setVerticalGroup(
            dpnAreaTrabalhoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });

        mnuCadatroUsuario.setText("Cadastrar");
        mnuCadatroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadatroUsuarioActionPerformed(evt);
            }
        });
        mnuCadatroUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuCadatroUsuarioKeyPressed(evt);
            }
        });
        mnuUsuarios.add(mnuCadatroUsuario);

        mnuExcluirUsuario.setText("Excluir");
        mnuExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuExcluirUsuario);

        mnuAlterarUsuario.setText("Alterar");
        mnuUsuarios.add(mnuAlterarUsuario);

        jMenuBar2.add(mnuUsuarios);

        mnuProdutos.setText("Produtos");

        mnuCadastrarProduto.setText("Cadastrar Produto");
        mnuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuCadastrarProduto);

        mnuRemoverProduto.setText("Remover Produto");
        mnuProdutos.add(mnuRemoverProduto);

        jMenuBar2.add(mnuProdutos);

        mnuSessao.setText("Sessão");

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuSessao.add(mnuSair);

        jMenuBar2.add(mnuSessao);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnAreaTrabalhoAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnAreaTrabalhoAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuCadatroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadatroUsuarioActionPerformed
        TelaCadastroUsuario telaCadUser = null;
        try {
            telaCadUser = new TelaCadastroUsuario(user.getNome());
        } catch (IOException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        dpnAreaTrabalhoAdmin.add(telaCadUser);
        telaCadUser.setVisible(true);
    }//GEN-LAST:event_mnuCadatroUsuarioActionPerformed

    private void mnuExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirUsuarioActionPerformed
        TelaExclusaoUsuario telaExUser = null;
        try {
            telaExUser = new TelaExclusaoUsuario(user.getNome());
        } catch (IOException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        dpnAreaTrabalhoAdmin.add(telaExUser);
        telaExUser.setVisible(true);
    }//GEN-LAST:event_mnuExcluirUsuarioActionPerformed

    private void mnuCadatroUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuCadatroUsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadatroUsuarioKeyPressed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        this.setVisible(false);
        try {
            new Log().atualizarLog(user.getNome(), "Logout");
        } catch (IOException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastrarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnAreaTrabalhoAdmin;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem mnuAlterarUsuario;
    private javax.swing.JMenuItem mnuCadastrarProduto;
    private javax.swing.JMenuItem mnuCadatroUsuario;
    private javax.swing.JMenuItem mnuExcluirUsuario;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenuItem mnuRemoverProduto;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSessao;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
